### ISSUE TITLE
Client and Server side materials.

### ISSUE THREAD

**Issue by WatIsDeze** [PolyhedronStudio/Polyhedron-Engine#11]
See whether we can make it fit in with the current .mat system. Seems logical to me to do so. This way, for example, a specific surface of a brush can have its own footstep style, or perhaps have them disabled. It is about control over such matters, decals for bullets that look different per material (we do not have them yet but still)

Other example would be how much friction it gives to the player movement.

**Comment by WatIsDeze** [comment]
Just picked a random few folks who know each their own share in the material world(what might belong in them), and about server/client -games development.

Enjoy, we're gonna do this one also.

**Comment by Admer456** [comment]
Just don't write separate classes for client and serverside materials. It's best to have a universal, generic way of accessing them.

**Comment by WatIsDeze** [comment]
> 
> 
> Just don't write separate classes for client and serverside materials. It's best to have a universal, generic way of accessing them.

As it stands, the code resides in the vkpt folder but is really quite unrelated to it. It'd perhaps require a bit of #if CL_GAME or #if SV_GAME here and there, which you can minimize. And as a result, it'd end up in sharedgame. So was my plan :)

**Comment by Paril** [comment]
> Just don't write separate classes for client and serverside materials. It's best to have a universal, generic way of accessing them.

This was my advice to him when we talked about it as well. Use a common parser that converts the on-disk representation into an in-memory one, and the various systems can pull out whatever data it needs from it. This is what we do in Quetoo with our materials as well.
