### ISSUE TITLE
Sun, night and day etc.

### ISSUE THREAD

**Issue by WatIsDeze** [PolyhedronStudio/Polyhedron-Engine#22]
Currently is controlled most often by the '/' key, however this should be done throughout the server instead. Perhaps there is room in configstrings, or we'd have to add some extra events. One way or the other, the server game has to rule over its domain where the sun may shine :)

**Comment by Admer456** [comment]
Oooh, this one's gonna be fun.

**Comment by WatIsDeze** [comment]
> 
> 
> Oooh, this one's gonna be fun.

Feel free to make it yours. Just use events instead of stuffcmd I suppose :P
