### ISSUE TITLE
Finish all basic C++ entity implementations.

### ISSUE THREAD

**Issue by WatIsDeze** [PolyhedronStudio/Polyhedron-Engine#3]
There is little to be said about this.

**Comment by WatIsDeze** [comment]
So far I ran into a problem with target_earthquake, I resolved it, but it was all coincidentally in my 60hz branch. 

I'll get back to this later, just writing it down here to let ya know. Reason why? It had to check with IsValidPointer | etc | etc first 👍

**Comment by WatIsDeze** [comment]
Forgot to link one of the PR's related to this.

**Comment by Admer456** [comment]
Just gonna put a list here of what's left to do:
- [ ] func_water
- [ ] func_breakable (func_explosive but more generic and sensible)
- [ ] func_conveyor
- [ ] func_killbox (kills everything in its volume when triggered)
- [ ] func_object (falls if there's nothing under it)
- [ ] func_plat (elevators etc.)
- [ ] info_player_deathmatch
- [ ] info_player_coop
- [ ] info_teledestination (generic misc_teleporter_destination)
- [ ] trigger_teleport (generic version of misc_teleporter) -> brush entity
- [ ] target_changelevel
- [ ] target_crosslevel_trigger
- [ ] target_crosslevel_target
- [ ] target_lightramp (lightstyle controller)
- [ ] target_spawner
- [ ] target_splash (throws various particle FX: lava blobs, sparks, blood etc.)
- [ ] trigger_elevator (intercepts a func_train to point to a respective "floor")
- [ ] trigger_key (item filter)
- [ ] trigger_monsterjump

**Comment by WatIsDeze** [comment]
Thanks for the list. I've already taken care of the info_player_deathmatch, and info_player_coop. (Although the the given gamemodes which they belong to do not respectfully check for randomness. (Closest to, furthest from, etc)

**Comment by Paril** [comment]
info_teledestination already exists: info_notnull fills that role as a generic point entity that can hold a position + direction

**Comment by Admer456** [comment]
A'ight, then those are all checked. :3
